services:
  monooki:
    build: .
    container_name: monooki
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      - JWT_SECRET=${JWT_SECRET:-XgU2Fp37EzHq6X3RhPqEndPMhCfYTWLE}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - DB_PATH=/app/data/monooki.db
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5175}
    volumes:
      - monooki_data:/app/data
      - monooki_uploads:/app/uploads
    networks:
      - monooki_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  monooki_data:
    driver: local
  monooki_uploads:
    driver: local

networks:
  monooki_network:
    driver: bridge 